# Generated by Django 2.2.2 on 2019-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbarras', models.BigIntegerField(unique=True, verbose_name='Codgio de Barras')),
                ('ubicacion', models.CharField(max_length=100)),
                ('nombre_activo', models.TextField()),
                ('nombre_comercial', models.TextField()),
                ('presentacion', models.TextField()),
                ('empaque', models.CharField(max_length=50)),
                ('dcantidad', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('mg', 'miligramos'), ('g', 'gramos'), ('ml', 'mililitros')], max_length=20, verbose_name='Unidad de medida')),
                ('presenta', models.CharField(choices=[('Tabletas', 'Tabletas'), ('Amp', 'Ampolletas'), ('Polv', 'Polvos'), ('Cap', 'Capsulas'), ('Pil', 'Pildoras'), ('Grag', 'Grageas'), ('Sup', 'Supositorios'), ('Ov', 'Ovulos'), ('Pom', 'Pomada'), ('Cre', 'Crema'), ('Sol', 'Soluciones'), ('Jar', 'Jarabes'), ('Col', 'Colirios'), ('Loc', 'Lociones'), ('Lin', 'Linimiento'), ('Eli', 'Elixir'), ('Ene', 'Enema'), ('Inha', 'Inhalaciones'), ('Aero', 'Aerosoles')], max_length=100)),
                ('gramaje', models.TextField()),
                ('cve_farmacia', models.IntegerField()),
                ('costo_venta', models.FloatField()),
                ('costo_compra', models.FloatField()),
                ('iva', models.IntegerField()),
                ('proveedor', models.TextField()),
                ('stock', models.IntegerField()),
                ('modificacion', models.CharField(max_length=3, null=True)),
                ('registro', models.CharField(max_length=20)),
                ('grupo', models.TextField(null=True)),
                ('laboratorio', models.TextField()),
                ('pais', models.TextField()),
                ('tlc', models.TextField()),
                ('pumpvp', models.FloatField()),
                ('modalidad_real', models.CharField(max_length=10)),
            ],
        ),
    ]
