# Generated by Django 2.2.2 on 2019-06-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbarras', models.PositiveIntegerField(unique=True, verbose_name='Codgio de Barras')),
                ('subcuenta', models.CharField(max_length=10)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('nombre_activo', models.CharField(max_length=200)),
                ('presentacion', models.CharField(choices=[('Tab', 'Tabletas'), ('Amp', 'Ampolletas'), ('Polv', 'Polvos'), ('Cap', 'Capsulas'), ('Pil', 'Pildoras'), ('Grag', 'Grageas'), ('Sup', 'Supositorios'), ('Ov', 'Ovulos'), ('Pom', 'Pomada'), ('Cre', 'Crema'), ('Sol', 'Soluciones'), ('Jar', 'Jarabes'), ('Col', 'Colirios'), ('Loc', 'Lociones'), ('Lin', 'Linimiento'), ('Eli', 'Elixir'), ('Ene', 'Enema'), ('Inha', 'Inhalaciones'), ('Aero', 'Aerosoles')], max_length=20)),
                ('cantidad_pastillas', models.PositiveIntegerField(verbose_name='Cantidad de pastillas')),
                ('unidad_medida', models.CharField(choices=[('mg', 'miligramos'), ('g', 'gramos'), ('ml', 'mililitros')], max_length=20, verbose_name='Unidad de medida')),
                ('precio_max_pub', models.PositiveIntegerField(verbose_name='Precio')),
            ],
        ),
    ]
