# Generated by Django 2.2.2 on 2019-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_name',
        ),
        migrations.AddField(
            model_name='product',
            name='nombre_activo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nombre_comercial',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='presentacion',
            field=models.CharField(choices=[('Tab', 'Tabletas'), ('Amp', 'Ampolletas'), ('Polv', 'Polvos'), ('Cap', 'Capsulas'), ('Pil', 'Pildoras'), ('Grag', 'Grageas'), ('Sup', 'Supositorios'), ('Ov', 'Ovulos'), ('Pom', 'Pomada'), ('Cre', 'Crema'), ('Sol', 'Soluciones'), ('Jar', 'Jarabes'), ('Col', 'Colirios'), ('Loc', 'Lociones'), ('Lin', 'Linimiento'), ('Eli', 'Elixir'), ('Ene', 'Enema'), ('Inha', 'Inhalaciones'), ('Aero', 'Aerosoles')], default='Tab', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='subcuenta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unidad_medida',
            field=models.CharField(choices=[('mg', 'miligramos'), ('g', 'gramos'), ('ml', 'mililitros')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
