# Generated by Django 2.2.2 on 2019-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cbarras',
            field=models.BigIntegerField(unique=True, verbose_name='Codgio de Barras'),
        ),
    ]
