# Generated by Django 2.2.2 on 2019-06-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modificacion',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
