# Generated by Django 2.2.2 on 2019-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190627_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grupo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
