# Generated by Django 2.2.2 on 2019-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190609_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad_pastillas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cbarras',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='miligramos',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
