# Generated by Django 2.2.2 on 2019-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190609_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cbarras',
            field=models.PositiveIntegerField(),
        ),
    ]
