# Generated by Django 2.2.2 on 2019-06-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190609_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='miligramos',
        ),
    ]
