# Generated by Django 2.2.2 on 2019-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_miligramos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio_max_pub',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
