# Generated by Django 2.2.2 on 2019-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_precio_max_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presentacion',
            field=models.CharField(choices=[('Tab', 'Tabletas'), ('Amp', 'Ampolletas'), ('Polv', 'Polvos'), ('Cap', 'Capsulas'), ('Pil', 'Pildoras'), ('Grag', 'Grageas'), ('Sup', 'Supositorios'), ('Ov', 'Ovulos'), ('Pom', 'Pomada'), ('Cre', 'Crema'), ('Sol', 'Soluciones'), ('Jar', 'Jarabes'), ('Col', 'Colirios'), ('Loc', 'Lociones'), ('Lin', 'Linimiento'), ('Eli', 'Elixir'), ('Ene', 'Enema'), ('Inha', 'Inhalaciones'), ('Aero', 'Aerosoles')], max_length=20),
        ),
    ]
