# Generated by Django 2.2.2 on 2019-06-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('farmacia', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name2', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50, unique=True)),
                ('calle_num', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
    ]
