# Generated by Django 2.2.2 on 2019-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
