# Generated by Django 2.2.2 on 2019-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20190608_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='farmacia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
