# Generated by Django 2.2.2 on 2019-06-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20190612_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='calle_num',
            field=models.CharField(max_length=100, verbose_name='Calle y numero'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cedula Profesional'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cp',
            field=models.CharField(max_length=10, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='estado',
            field=models.CharField(choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIA', 'Chiapas'), ('CHIH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('EDOMEX', 'Estado de Mexico'), ('GTO', 'Guanajuato'), ('GRRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MICH', 'Michoacan'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Queretaro'), ('QUROO', 'Quintana Roo'), ('SLP', 'San Luis Potosi'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatan'), ('ZAC', 'Zacatecas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name2',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
