# Generated by Django 2.2.2 on 2019-06-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_doctor_farmacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rfc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
