# Generated by Django 2.2.2 on 2019-06-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_capturista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturista',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Farmacia'),
        ),
    ]
