# Generated by Django 2.2.2 on 2019-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190613_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturista',
            name='apellidos',
            field=models.CharField(default='Andres', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capturista',
            name='nombre',
            field=models.CharField(default='Quiroz', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerente',
            name='apellidos',
            field=models.CharField(default='Quiroz', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerente',
            name='nombre',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
