# Generated by Django 2.2.2 on 2019-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190614_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturista',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerente',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
