# Generated by Django 2.2.2 on 2019-06-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('descripcion_equivalente', models.CharField(max_length=50)),
                ('cbarras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbarras1', to='products.Product')),
                ('cbarras_equivalente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbarras2', to='products.Product')),
            ],
        ),
    ]
