# Generated by Django 2.2.2 on 2019-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbarras', models.TextField()),
                ('descripcion', models.TextField()),
                ('cbarras_equivalente', models.TextField()),
                ('descripcion_equivalente', models.TextField()),
                ('cantidad_equivalente', models.TextField()),
            ],
        ),
    ]
