# Generated by Django 2.2.2 on 2019-06-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbarras', models.PositiveIntegerField(verbose_name='Codgio de Barras')),
                ('subcuenta', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('nombre_activo', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=50)),
                ('cantidad_pastillas', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('precio_max_pub', models.PositiveIntegerField()),
            ],
        ),
    ]
