# Generated by Django 2.2.2 on 2019-06-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalencia',
            name='cantidad_equivalente',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='cbarras',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='cbarras_equivalente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='descripcion_equivalente',
            field=models.TextField(max_length=200),
        ),
    ]
