# Generated by Django 2.2.2 on 2019-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalencia',
            name='cantidad_equivalente',
            field=models.FloatField(max_length=50),
        ),
    ]
