# Generated by Django 2.2.2 on 2019-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
        ('derechohabiente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derechohabiente',
            name='cve_farmacia',
        ),
        migrations.AddField(
            model_name='derechohabiente',
            name='farmacia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmacia.Farmacia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='derechohabiente',
            name='org',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
