# Generated by Django 2.2.2 on 2019-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derechohabiente', '0002_auto_20190618_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derechohabiente',
            name='org',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
