# Generated by Django 2.2.2 on 2019-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derechohabiente', '0003_auto_20190618_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derechohabiente',
            name='org',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
