# Generated by Django 2.2.2 on 2019-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nur',
            field=models.CharField(max_length=255, unique=True, verbose_name='NUR'),
        ),
    ]
