# Generated by Django 2.2.2 on 2019-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='creado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_expide',
            field=models.DateTimeField(verbose_name='Fecha de expedicion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_recibe',
            field=models.DateTimeField(verbose_name='Fecha que recibe'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_surte',
            field=models.DateTimeField(verbose_name='Fecha que surte'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ultimamodif',
            field=models.DateTimeField(),
        ),
    ]
