# Generated by Django 2.2.2 on 2019-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='farmacia',
            field=models.CharField(max_length=20),
        ),
    ]
