# Generated by Django 2.2.2 on 2019-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='NUR',
            field=models.CharField(max_length=255),
        ),
    ]
