# Generated by Django 2.2.2 on 2020-01-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_auto_20191106_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='creado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_expide',
            field=models.DateField(verbose_name='Fecha de expedicion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_recibe',
            field=models.DateField(verbose_name='Fecha que recibe'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha_surte',
            field=models.DateField(verbose_name='Fecha que surte'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ultimamodif',
            field=models.DateField(),
        ),
    ]
