# Generated by Django 2.2.2 on 2019-06-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_auto_20190619_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='doctor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Farmacia'),
        ),
    ]
