# Generated by Django 2.2.2 on 2019-06-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_receta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='folio_receta',
            field=models.CharField(max_length=255, verbose_name='Folio de Receta'),
        ),
    ]
