# Generated by Django 2.2.2 on 2019-06-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_auto_20190619_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor'),
        ),
    ]
