# Generated by Django 2.2.2 on 2019-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_auto_20190619_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
