# Generated by Django 2.2.2 on 2019-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0006_auto_20190625_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ficha_derechohabiente',
            field=models.CharField(max_length=100),
        ),
    ]
