# Generated by Django 2.2.2 on 2019-06-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0008_auto_20190626_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ficha_derechohabiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derechohabiente.DerechoHabiente'),
        ),
    ]
