# Generated by Django 2.2.2 on 2019-06-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0009_auto_20190626_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='cbarras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor'),
        ),
    ]
