# Generated by Django 2.2.2 on 2019-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0010_auto_20190626_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
