# Generated by Django 2.2.2 on 2019-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0011_auto_20190626_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='has_Equivalencia',
            field=models.BooleanField(default=False),
        ),
    ]
