# Generated by Django 2.2.2 on 2019-06-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0012_receta_has_equivalencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='equivalencia_cantidad',
        ),
    ]
